name: weather_app
description: Chapters 4 - 6, Flutter in Action by Eric Windmill
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.8.0

dev_dependencies:
  build_runner: "^1.1.1"
  built_value_generator: "^6.1.6"

flutter:
  uses-material-design: true
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.otf
        - asset: assets/fonts/Cabin-Bold.otf
        - asset: assets/fonts/Cabin-Italic.otf
        - asset: assets/fonts/Cabin-Medium.otf
        - asset: assets/fonts/Cabin-BoldItalic.otf
        - asset: assets/fonts/Cabin-MediumItalic.otf
        - asset: assets/fonts/Cabin-SemiBold.otf
        - asset: assets/fonts/Cabin-SemiBoldItalic.otf